### ISSUE TITLE
stage1-only: .gitignore file is copied into INSTALL_DIR

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#131]
Yesterday, I switched in my `stage1-only` build to `/opt/llvm-toolchain` as `INSTALL_DIR` and see:
```
$ cd /path/to/tc-build/git
$ python3 ./build-llvm.py --no-update --build-type Release -p clang;lld -t X86;BPF;AArch64 --clang-vendor dileks -B /home/dileks/src/llvm-toolchain/build -I /opt/llvm-toolchain --check-targets clang lld --build-stage1-only --install-stage1-only

$ LC_ALL=C ls -alh /opt/llvm-toolchain/.gitignore
-rw-r--r-- 1 dileks dileks 1 Jan 14 20:48 /opt/llvm-toolchain/.gitignore
```

**Comment by nathanchance** [comment]
This is intentional:

https://github.com/ClangBuiltLinux/tc-build/blob/master/build-llvm.py#L972

https://github.com/ClangBuiltLinux/tc-build/blob/2390492e2581f9d41a2d7279b53789dd782e7178/utils.py#L10

If you install the toolchain into a folder that is git tracked (for example, the default `install` location within the `tc-build` repo), you risk adding it with `git add`.

**Comment by dileks** [comment]
OK, I see.

Thanks.
You wanna close this issue or shall I do?
