### ISSUE TITLE
[Question] Does build-llvm.py need an update for clang-14?

### ISSUE THREAD

**Issue by torvic9** [ClangBuiltLinux/tc-build#181]
I ran into some cmake warnings when building from 'release/14.x' branch:

```
CMake Warning at /path/tc-build/llvm-project/compiler-rt/cmake/Modules/CompilerRTUtils.cmake:352 (message):
  llvm-config finding testingsupport failed with status 1
Call Stack (most recent call first):
  CMakeLists.txt:28 (load_llvm_config)
```

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    HAVE_LLVM_LIT
    LLVM_DEFAULT_TARGET_TRIPLE
    LLVM_HAVE_LINK_VERSION_SCRIPT
    LLVM_SOURCE_PREFIX
    LLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO
    LLVM_USE_RELATIVE_PATHS_IN_FILES
```

```
CMake Warning:
  Manually-specified variables were not used by the project:

    HAVE_LLVM_LIT
    LLVM_BUILD_TOOLS
```

Built with Arch's clang 13.0.1, the following build parameters were used:
```
-p "clang;lld" \
--lto thin \
--no-ccache \
--check-targets clang \
-t "X86" \
-D \
    CMAKE_C_FLAGS="-march=skylake -O2 -pipe" \
    CMAKE_CXX_FLAGS="-march=skylake -O2 -pipe" \
    LLVM_ENABLE_RUNTIMES="compiler-rt" \
-b release/14.x
```

N.B.: I added compiler-rt to `LLVM_ENABLE_RUNTIMES` because of [this commit](https://github.com/llvm/llvm-project/commit/c8bb1777fff5d1ae28a2deac0d6677e081d4200f).

**Comment by RuRuTiaSaMa** [comment]
https://github.com/Panchajanya1999/tc-build/commits/master@b9fd431

**Comment by nathanchance** [comment]
`LLVM_ENABLE_RUNTIMES` is not been deprecated for `compiler-rt` yet (it seems at least):

https://github.com/llvm/llvm-project/blob/175d5fa388298934629f5cf183c7de45a672a063/llvm/CMakeLists.txt#L87-L92

I would recommend sticking with adding it via `--projects` as @RuRuTiaSaMa mentioned.

Regardless, `CMAKE_CXX_COMPILER` is the only `cmake` define that the script provides, all the other ones appear to come from an internal `cmake` file, so these warnings would be better reported to LLVM developers upstream (if they even matter). I would use `--show-build-commands` to extract the `ninja` command from the script so that LLVM developers don't have to use the script to reproduce.
