### ISSUE TITLE
Cross toolchain question

### ISSUE THREAD

**Issue by wctrl** [ClangBuiltLinux/tc-build#267]
Hello again, before I used some prebuilt toolchain and it had `aarch64-linux-gnu-*` (* means tools like ar, objcopy, ...) in bin folder. But toolchain what I built using this repo don't have that (targets was x86, arm, aarch64). Am I miss something?

**Comment by nathanchance** [comment]
`clang` is multi-targeted by default unlike GCC, so it builds code for both the host and cross architectures through the `--target` flag.

**Comment by wctrl** [comment]
Yes, but Linux cross-compile cmdline looks like `make -j8 O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CC=clang READELF=llvm-readelf OBJCOPY=llvm-objcopy AS=llvm-as LD=ld.lld NM=llvm-nm OBJDUMP=llvm-objdump STRIP=llvm-strip CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1` without `CROSS_COMPILE` it won't build vDSO. Is `aarch64-linux-gnu-*` thing called binutils?

**Comment by nathanchance** [comment]
> Is `aarch64-linux-gnu-*` thing called binutils?

Yes.

`CROSS_COMPILE` has two meanings depending on the age of the kernel tree. It is used to prefix `as`, `gcc`, `ld`, etc but it is also used as the value for `--target` prior to commit [ddc72c9659b5](https://git.kernel.org/linus/ddc72c9659b5a85a2d135503caf193da0723e813) ("kbuild: clang: do not use CROSS_COMPILE for target triple") (same with `CROSS_COMPILE_ARM32` but for the 32-bit vDSO). Since you have specified all the make variables that would have been prefixed with `CROSS_COMPILE`, you would think that you could drop it, but it is still being used for `--target`. You don't need the `aarch64-linux-gnu-` tools as a result.

Two additional comments about your build command:

1. `LLVM=1` is the same thing as `AR=llvm-ar CC=clang LD=ld.lld NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf STRIP=llvm-strip`, you don't need to specify both.
2. `AS=llvm-as` is incorrect, as `$(AS)` does not exist after commit [aa824e0c962b](https://git.kernel.org/linus/aa824e0c962b532d5073cbb41b2efcd6f5e72bae) ("kbuild: remove AS variable") and even if it did, `llvm-as` is the LLVM IR to bitcode assembler. You are looking for `LLVM_IAS=1` if you want to use the integrated assembler.

**Comment by nathanchance** [comment]
Yes, that is why `build-binutils.py` exists, you can get the `aarch64-linux-gnu` tools via `build-binutils.py -t aarch64` (see `-h` for more options if you need them).

**Comment by wctrl** [comment]
Thanks! For someone who will find that: I prefixed them with `./build-binutils.py -i target_dir -t aarch64` and binutils will be in `target_dir/bin/`
