### ISSUE TITLE
Toolchain from kernel.org shipped without polly

### ISSUE THREAD

**Issue by wctrl** [ClangBuiltLinux/tc-build#281]
Is this how it's supposed to be? The build script says that polly is already selected by default

Extra info: version: `ClangBuiltLinux clang version 19.1.2`
Check polly: `clang -mllvm --help init/main.c | grep polly` (will fail without any input file)

**Comment by nathanchance** [comment]
The kernel.org toolchains are built using tc-build but I used a different set of projects: https://github.com/nathanchance/env/blob/879b5ed9f156adb2f2bae115e55f2d5058a08f36/python/pgo-llvm-builder/build.py#L174-L178

While it was not entirely intentional to omit `polly` from that list, I am not really inclined to add it because there has been little empirical evidence that the Linux kernel benefits from polyhedral optimizations. There was [a patch](https://lore.kernel.org/all/20210120174146.12287-1-lazerl0rd@thezest.dev/) submitted upstream with some numbers but they did not really seem convincing to me and there was nobody else who stepped up to help test and benchmark.

**Comment by wctrl** [comment]
I see, thanks!
